language: php

addons:
  code_climate:
    repo_token: 6b6332b313557456f1fcf49cd1b9fbddfa0c042e43d92a9d19080f8ab32e1de8

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction --dev

script:
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter
